### ISSUE TITLE
Dataset: viewing datasets result in 500 error, post 5.1 deployment

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse.harvard.edu#83]
Clicking on either results in 500 error. They were added soon after 5.1 deployment.

 https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SSBOLA
 https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/Z834IK

```
[2020-10-07T10:33:28.465-0400] [Payara 5.2020] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] [tid: _ThreadID=262 _ThreadName=http-thread-pool::jk-connector(7)] [timeMillis: 1602081208465] [levelValue: 1000] [[
 Error Rendering View[/dataset.xhtml]
javax.el.ELException: /dataset.xhtml @59,66 value="#{DatasetPage.jsonLd}": java.lang.NullPointerException
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:77)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:170)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:157)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:140)
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getValue(HtmlBasicInputRenderer.java:181)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(HtmlBasicRenderer.java:328)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(HtmlBasicRenderer.java:143)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at org.primefaces.renderkit.HeadRenderer.encodeBegin(HeadRenderer.java:72)
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:540)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1644)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:368)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.el.ELException: java.lang.NullPointerException
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:304)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:156)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:184)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:114)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:177)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:183)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
	... 58 more
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DataFile.getDerivedOriginalFileName(DataFile.java:456)
	at edu.harvard.iq.dataverse.DataFile.getOriginalFileName(DataFile.java:447)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.json(JsonPrinter.java:608)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.json(JsonPrinter.java:562)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.jsonFileMetadatas(JsonPrinter.java:445)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.json(JsonPrinter.java:365)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.jsonWithCitation(JsonPrinter.java:419)
	at edu.harvard.iq.dataverse.util.json.JsonPrinter.jsonAsDatasetDto(JsonPrinter.java:438)
	at edu.harvard.iq.dataverse.export.ExportService.exportFormat(ExportService.java:211)
	at edu.harvard.iq.dataverse.export.ExportService.getExport(ExportService.java:99)
	at edu.harvard.iq.dataverse.export.ExportService.getExportAsString(ExportService.java:118)
	at edu.harvard.iq.dataverse.DatasetPage.getJsonLd(DatasetPage.java:5486)
	at sun.reflect.GeneratedMethodAccessor1192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:299)
	... 65 more
]]
```

**Comment by landreev** [comment]
OK, we know what it was. 
The 2 datasets should be working now.

**Comment by landreev** [comment]
This was indirectly cause by the earlier S3 issues; specifically, metadata exports failed when these datasets were published. And, apparently, if the "schema.org" (aka "LD JSON") is not cached for a published dataset, trying to generate it on the fly bombs with that null pointer, when the export is called from the page. 
Exporting the format via the API however fixes it.
This must be an issue much older than 5.1 - but apparently we never (normally don't) see it because the format is always already exported by the time the page tries to access it. (but we'll need an issue for it in the main project).

**Comment by landreev** [comment]
I'll look at other datasets that have been published since yesterday.

**Comment by mheppler** [comment]
Maybe this? **Export during publication finalization should not fail with NullPointerException and show dataset as "unpublished" https://github.com/IQSS/dataverse/issues/5759**

**Comment by landreev** [comment]
Not even close.

**Comment by landreev** [comment]
OK, these 2 datasets were the only ones affected.

**Comment by landreev** [comment]
We can close this issue now - but let's do that *after* we open an issue in the main project, for the weird null pointer failure/missing filemetadata entity when the export is being called on page load (so that we don't forget).

**Comment by mheppler** [comment]
Well, it had "_dataset_", "_export_" and "_nullPointer_" in the issue title, all keywords pulled from your comment describing an older issue. So I'd argue your definition of "_close_".

**Comment by kcondon** [comment]
@landreev Are you going to open the new issue?

**Comment by landreev** [comment]
Thanks - will edit.
